export const POST_USER_REGISTERATION_KEY =
  'POST_USER_REGISTERATION_KEY';
export const POST_USER_VERIFICATION_KEY =
  'POST_USER_VERIFICATION_KEY';
export const POST_USER_LOGIN_KEY = 'POST_USER_LOGIN_KEY';
export const GET_REFRESH_TOKEN_KEY = 'GET_REFRESH_TOKEN_KEY';
export const POST_FORGOT_USER_PASSWORD_KEY =
  'POST_FORGOT_USER_PASSWORD_KEY';
export const POST_RESET_USER_PASSWORD_KEY =
  'POST_RESET_USER_PASSWORD_KEY';
export const POST_REFRESH_TOKEN_KEY = 'POST_REFRESH_TOKEN_KEY';
